service: sls-go-pg-rest-demo

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  stage: ${opt:stage}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
        - 'secretsmanager:GetSecretValue'
        - 'secretsmanager:DescribeSecret'
        - 'ssm:GetParameterHistory'
        - 'ssm:ListTagsForResource'
        - 'ssm:GetParametersByPath'
        - 'ssm:GetParameters'
        - 'ssm:GetParameter'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'kms:Decrypt'
        - 'kms:DescribeKey'
      Resource: '*'

functions:
  api:
    handler: bin/api
    memorySize: 128
    description: Serverless Go REST API Demo
    package:
      include:
        - ./bin/api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
